"""
Django settings for PqaWeb project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

IS_PRODUCTION = not (len(sys.argv) >= 1 and sys.argv[0].endswith('manage.py'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = Path(os.path.join(BASE_DIR, '../../secret/django_key.txt')).read_text()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not IS_PRODUCTION

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]', '192.168.100.103', '86.57.175.52', '82.209.232.105', 'probqa.com',
                 'www.probqa.com', 'best-games.info', 'www.best-games.info']


# Application definition

INSTALLED_APPS = [
    'pqawV1.apps.Pqawv1Config',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PqaWeb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PqaWeb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'read_default_file': os.path.join(BASE_DIR, '../../secret/my.cnf'),
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.realpath(os.path.join(BASE_DIR, '../../Data/StaticRoot'))

# Tweaking Django
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'

# Media files (e.g. uploads)
MEDIA_ROOT = os.path.realpath(os.path.join(BASE_DIR, '../../Data/MediaRoot'))

MEDIA_URL = '/media/'


# KB (knowledge base) files and configuration
KB_ROOT = os.path.join(BASE_DIR, '../../Data/KBs/')
PQA_N_ANSWERS = 5  # PQA - Probabilistic Question Asking
PQA_TOP_TARGETS = 10
PQA_MIN_TARGETS = 2
PQA_MIN_QUESTIONS = 1

# Backup
ARCHIVE_DIRECTORY = 'E:/Backup/ProbQA/WebSite/'
ARCHIVE_FORMAT = 'bz2'  # The options are 'gz' and 'bz2'

# Configuration of periodic tasks and quiz cache
CLEAR_OLD_QUIZZES_CHECK_PERIOD_SEC = 60  # check each minute
CLEAR_QUIZZES_AGE_SEC = 60 * 20  # clear cache if older than 20 minutes
CLEAR_QUIZZES_IF_COUNT_EXCEEDS = 7777  # About 1GB of RAM for 10 000 targets
SAVE_ENGINE_PERIOD_SEC = 60 * 30  # Save engine each 30 minutes

# Security settings
# SECURE_CONTENT_TYPE_NOSNIFF = True
# SECURE_BROWSER_XSS_FILTER = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
