# Generated by Django 2.1.4 on 2018-12-29 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('option_pos', models.BigIntegerField(verbose_name='Option position number')),
                ('message', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pqa_id', models.BigIntegerField(null=True, unique=True, verbose_name='Permanent question identifier inside the engine')),
                ('message', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pqa_id', models.BigIntegerField(null=True, unique=True, verbose_name='Permanent target identifier inside the engine')),
                ('title', models.CharField(max_length=255)),
                ('link', models.TextField(max_length=65535)),
                ('image', models.BinaryField(max_length=16777215)),
                ('description', models.TextField(max_length=65535)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pqawV1.Question'),
        ),
    ]
