# Generated by Django 2.1.4 on 2019-01-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqawV1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='username',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
