# Generated by Django 2.1.4 on 2018-12-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqawV1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='image',
            field=models.ImageField(max_length=255, upload_to='Uploads/TargetImages/%Y/%m/%d/'),
        ),
    ]
