# Generated by Django 2.1.4 on 2019-01-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqawV1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='pqa_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Permanent ID in engine'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pqa_id',
            field=models.BigIntegerField(db_index=True, unique=True, verbose_name='Permanent ID in engine'),
        ),
        migrations.AlterField(
            model_name='target',
            name='pqa_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Permanent ID in engine'),
        ),
    ]
