# Generated by Django 2.1.4 on 2019-02-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqawV1', '0002_auto_20190119_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='Uploads/TargetThumbnails/%Y/%m/%d/'),
        ),
    ]
