# Generated by Django 2.1.4 on 2019-01-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqawV1', '0002_auto_20181230_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='to_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='pqa_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Permanent ID in engine'),
        ),
        migrations.AlterField(
            model_name='target',
            name='pqa_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Permanent ID in engine'),
        ),
    ]
