# Generated by Django 2.1.4 on 2019-01-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqawV1', '0003_auto_20190105_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='to_delete',
            field=models.BooleanField(default=False),
        ),
    ]
