# Generated by Django 2.1.4 on 2019-01-12 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pqawV1', '0006_knowledgebase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pqa_id', models.BigIntegerField(unique=True, verbose_name='Permanent ID in engine')),
                ('user_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pqawV1.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pqawV1.Question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pqawV1.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizTarget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_choice_id', models.BigIntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pqawV1.Quiz')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pqawV1.Target')),
            ],
        ),
    ]
